//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated. 
// </auto-generated>
//------------------------------------------------------------------------------

namespace JAFrontendWeb.Account {
    
    
    public partial class ViewApplicant {
        
        /// <summary>
        /// viewApplicant control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::JAFrontendWeb.controls.ViewApplicant viewApplicant;
        
        /// <summary>
        /// userNav control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::JAFrontendWeb.controls.UserNavigation userNav;
        
        /// <summary>
        /// Master property.
        /// </summary>
        /// <remarks>
        /// Auto-generated property.
        /// </remarks>
        public new JAFrontendWeb.MasterPages.Secondary Master {
            get {
                return ((JAFrontendWeb.MasterPages.Secondary)(base.Master));
            }
        }
    }
}
