//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by Microsoft.VSDesigner, Version 4.0.30319.42000.
// 
#pragma warning disable 1591

namespace JAFrontendWeb.com.jabackendservice {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.Xml.Serialization;
    using System.ComponentModel;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2053.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="JAServiceSoap", Namespace="http://tempuri.org/")]
    public partial class JAService : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback AddApplicantOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetLocationsOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetIndustriesOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetSalaryRangesOperationCompleted;
        
        private System.Threading.SendOrPostCallback RetrieveApplicantListByPagingOperationCompleted;
        
        private System.Threading.SendOrPostCallback RetrieveAllApplicantsOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public JAService() {
            this.Url = global::JAFrontendWeb.Properties.Settings.Default.JAFrontendWeb_com_jabackendservice_JAService;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event AddApplicantCompletedEventHandler AddApplicantCompleted;
        
        /// <remarks/>
        public event GetLocationsCompletedEventHandler GetLocationsCompleted;
        
        /// <remarks/>
        public event GetIndustriesCompletedEventHandler GetIndustriesCompleted;
        
        /// <remarks/>
        public event GetSalaryRangesCompletedEventHandler GetSalaryRangesCompleted;
        
        /// <remarks/>
        public event RetrieveApplicantListByPagingCompletedEventHandler RetrieveApplicantListByPagingCompleted;
        
        /// <remarks/>
        public event RetrieveAllApplicantsCompletedEventHandler RetrieveAllApplicantsCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/AddApplicant", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public int AddApplicant(string jsonUser, out string message) {
            object[] results = this.Invoke("AddApplicant", new object[] {
                        jsonUser});
            message = ((string)(results[1]));
            return ((int)(results[0]));
        }
        
        /// <remarks/>
        public void AddApplicantAsync(string jsonUser) {
            this.AddApplicantAsync(jsonUser, null);
        }
        
        /// <remarks/>
        public void AddApplicantAsync(string jsonUser, object userState) {
            if ((this.AddApplicantOperationCompleted == null)) {
                this.AddApplicantOperationCompleted = new System.Threading.SendOrPostCallback(this.OnAddApplicantOperationCompleted);
            }
            this.InvokeAsync("AddApplicant", new object[] {
                        jsonUser}, this.AddApplicantOperationCompleted, userState);
        }
        
        private void OnAddApplicantOperationCompleted(object arg) {
            if ((this.AddApplicantCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.AddApplicantCompleted(this, new AddApplicantCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/GetLocations", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public LocationDto[] GetLocations() {
            object[] results = this.Invoke("GetLocations", new object[0]);
            return ((LocationDto[])(results[0]));
        }
        
        /// <remarks/>
        public void GetLocationsAsync() {
            this.GetLocationsAsync(null);
        }
        
        /// <remarks/>
        public void GetLocationsAsync(object userState) {
            if ((this.GetLocationsOperationCompleted == null)) {
                this.GetLocationsOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetLocationsOperationCompleted);
            }
            this.InvokeAsync("GetLocations", new object[0], this.GetLocationsOperationCompleted, userState);
        }
        
        private void OnGetLocationsOperationCompleted(object arg) {
            if ((this.GetLocationsCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetLocationsCompleted(this, new GetLocationsCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/GetIndustries", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public IndustryDto[] GetIndustries() {
            object[] results = this.Invoke("GetIndustries", new object[0]);
            return ((IndustryDto[])(results[0]));
        }
        
        /// <remarks/>
        public void GetIndustriesAsync() {
            this.GetIndustriesAsync(null);
        }
        
        /// <remarks/>
        public void GetIndustriesAsync(object userState) {
            if ((this.GetIndustriesOperationCompleted == null)) {
                this.GetIndustriesOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetIndustriesOperationCompleted);
            }
            this.InvokeAsync("GetIndustries", new object[0], this.GetIndustriesOperationCompleted, userState);
        }
        
        private void OnGetIndustriesOperationCompleted(object arg) {
            if ((this.GetIndustriesCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetIndustriesCompleted(this, new GetIndustriesCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/GetSalaryRanges", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public SalaryRangeDto[] GetSalaryRanges() {
            object[] results = this.Invoke("GetSalaryRanges", new object[0]);
            return ((SalaryRangeDto[])(results[0]));
        }
        
        /// <remarks/>
        public void GetSalaryRangesAsync() {
            this.GetSalaryRangesAsync(null);
        }
        
        /// <remarks/>
        public void GetSalaryRangesAsync(object userState) {
            if ((this.GetSalaryRangesOperationCompleted == null)) {
                this.GetSalaryRangesOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetSalaryRangesOperationCompleted);
            }
            this.InvokeAsync("GetSalaryRanges", new object[0], this.GetSalaryRangesOperationCompleted, userState);
        }
        
        private void OnGetSalaryRangesOperationCompleted(object arg) {
            if ((this.GetSalaryRangesCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetSalaryRangesCompleted(this, new GetSalaryRangesCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/RetrieveApplicantListByPaging", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public ApplicantDto[] RetrieveApplicantListByPaging(int pageSize, int pageIndex) {
            object[] results = this.Invoke("RetrieveApplicantListByPaging", new object[] {
                        pageSize,
                        pageIndex});
            return ((ApplicantDto[])(results[0]));
        }
        
        /// <remarks/>
        public void RetrieveApplicantListByPagingAsync(int pageSize, int pageIndex) {
            this.RetrieveApplicantListByPagingAsync(pageSize, pageIndex, null);
        }
        
        /// <remarks/>
        public void RetrieveApplicantListByPagingAsync(int pageSize, int pageIndex, object userState) {
            if ((this.RetrieveApplicantListByPagingOperationCompleted == null)) {
                this.RetrieveApplicantListByPagingOperationCompleted = new System.Threading.SendOrPostCallback(this.OnRetrieveApplicantListByPagingOperationCompleted);
            }
            this.InvokeAsync("RetrieveApplicantListByPaging", new object[] {
                        pageSize,
                        pageIndex}, this.RetrieveApplicantListByPagingOperationCompleted, userState);
        }
        
        private void OnRetrieveApplicantListByPagingOperationCompleted(object arg) {
            if ((this.RetrieveApplicantListByPagingCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.RetrieveApplicantListByPagingCompleted(this, new RetrieveApplicantListByPagingCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/RetrieveAllApplicants", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public ApplicantDto[] RetrieveAllApplicants() {
            object[] results = this.Invoke("RetrieveAllApplicants", new object[0]);
            return ((ApplicantDto[])(results[0]));
        }
        
        /// <remarks/>
        public void RetrieveAllApplicantsAsync() {
            this.RetrieveAllApplicantsAsync(null);
        }
        
        /// <remarks/>
        public void RetrieveAllApplicantsAsync(object userState) {
            if ((this.RetrieveAllApplicantsOperationCompleted == null)) {
                this.RetrieveAllApplicantsOperationCompleted = new System.Threading.SendOrPostCallback(this.OnRetrieveAllApplicantsOperationCompleted);
            }
            this.InvokeAsync("RetrieveAllApplicants", new object[0], this.RetrieveAllApplicantsOperationCompleted, userState);
        }
        
        private void OnRetrieveAllApplicantsOperationCompleted(object arg) {
            if ((this.RetrieveAllApplicantsCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.RetrieveAllApplicantsCompleted(this, new RetrieveAllApplicantsCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2102.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class LocationDto {
        
        private int locationIdField;
        
        private int subLocationIdField;
        
        private string locationNameField;
        
        private string subLocationNameField;
        
        /// <remarks/>
        public int LocationId {
            get {
                return this.locationIdField;
            }
            set {
                this.locationIdField = value;
            }
        }
        
        /// <remarks/>
        public int SubLocationId {
            get {
                return this.subLocationIdField;
            }
            set {
                this.subLocationIdField = value;
            }
        }
        
        /// <remarks/>
        public string LocationName {
            get {
                return this.locationNameField;
            }
            set {
                this.locationNameField = value;
            }
        }
        
        /// <remarks/>
        public string SubLocationName {
            get {
                return this.subLocationNameField;
            }
            set {
                this.subLocationNameField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2102.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class ApplicantDto {
        
        private int applicantIdField;
        
        private string firstNameField;
        
        private string lastNameField;
        
        private string companyNameField;
        
        private string phoneField;
        
        private string emailField;
        
        private string correspondenceAddressField;
        
        private string jobTitleField;
        
        private string jobSpecificationField;
        
        private int locationIdField;
        
        private string locationNameField;
        
        private int subLocationIdField;
        
        private string subLocationNameField;
        
        private int industryIdField;
        
        private string industryNameField;
        
        private int salaryRangeIdField;
        
        private string salaryRangeField;
        
        private System.DateTime creationDateField;
        
        /// <remarks/>
        public int ApplicantId {
            get {
                return this.applicantIdField;
            }
            set {
                this.applicantIdField = value;
            }
        }
        
        /// <remarks/>
        public string FirstName {
            get {
                return this.firstNameField;
            }
            set {
                this.firstNameField = value;
            }
        }
        
        /// <remarks/>
        public string LastName {
            get {
                return this.lastNameField;
            }
            set {
                this.lastNameField = value;
            }
        }
        
        /// <remarks/>
        public string CompanyName {
            get {
                return this.companyNameField;
            }
            set {
                this.companyNameField = value;
            }
        }
        
        /// <remarks/>
        public string Phone {
            get {
                return this.phoneField;
            }
            set {
                this.phoneField = value;
            }
        }
        
        /// <remarks/>
        public string Email {
            get {
                return this.emailField;
            }
            set {
                this.emailField = value;
            }
        }
        
        /// <remarks/>
        public string CorrespondenceAddress {
            get {
                return this.correspondenceAddressField;
            }
            set {
                this.correspondenceAddressField = value;
            }
        }
        
        /// <remarks/>
        public string JobTitle {
            get {
                return this.jobTitleField;
            }
            set {
                this.jobTitleField = value;
            }
        }
        
        /// <remarks/>
        public string JobSpecification {
            get {
                return this.jobSpecificationField;
            }
            set {
                this.jobSpecificationField = value;
            }
        }
        
        /// <remarks/>
        public int LocationId {
            get {
                return this.locationIdField;
            }
            set {
                this.locationIdField = value;
            }
        }
        
        /// <remarks/>
        public string LocationName {
            get {
                return this.locationNameField;
            }
            set {
                this.locationNameField = value;
            }
        }
        
        /// <remarks/>
        public int SubLocationId {
            get {
                return this.subLocationIdField;
            }
            set {
                this.subLocationIdField = value;
            }
        }
        
        /// <remarks/>
        public string SubLocationName {
            get {
                return this.subLocationNameField;
            }
            set {
                this.subLocationNameField = value;
            }
        }
        
        /// <remarks/>
        public int IndustryId {
            get {
                return this.industryIdField;
            }
            set {
                this.industryIdField = value;
            }
        }
        
        /// <remarks/>
        public string IndustryName {
            get {
                return this.industryNameField;
            }
            set {
                this.industryNameField = value;
            }
        }
        
        /// <remarks/>
        public int SalaryRangeId {
            get {
                return this.salaryRangeIdField;
            }
            set {
                this.salaryRangeIdField = value;
            }
        }
        
        /// <remarks/>
        public string SalaryRange {
            get {
                return this.salaryRangeField;
            }
            set {
                this.salaryRangeField = value;
            }
        }
        
        /// <remarks/>
        public System.DateTime CreationDate {
            get {
                return this.creationDateField;
            }
            set {
                this.creationDateField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2102.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class SalaryRangeDto {
        
        private int salaryRangeIdField;
        
        private string displayField;
        
        /// <remarks/>
        public int SalaryRangeId {
            get {
                return this.salaryRangeIdField;
            }
            set {
                this.salaryRangeIdField = value;
            }
        }
        
        /// <remarks/>
        public string Display {
            get {
                return this.displayField;
            }
            set {
                this.displayField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2102.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class IndustryDto {
        
        private int industryIdField;
        
        private string industryNameField;
        
        /// <remarks/>
        public int IndustryId {
            get {
                return this.industryIdField;
            }
            set {
                this.industryIdField = value;
            }
        }
        
        /// <remarks/>
        public string IndustryName {
            get {
                return this.industryNameField;
            }
            set {
                this.industryNameField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2053.0")]
    public delegate void AddApplicantCompletedEventHandler(object sender, AddApplicantCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2053.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class AddApplicantCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal AddApplicantCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public int Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((int)(this.results[0]));
            }
        }
        
        /// <remarks/>
        public string message {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[1]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2053.0")]
    public delegate void GetLocationsCompletedEventHandler(object sender, GetLocationsCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2053.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetLocationsCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetLocationsCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public LocationDto[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((LocationDto[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2053.0")]
    public delegate void GetIndustriesCompletedEventHandler(object sender, GetIndustriesCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2053.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetIndustriesCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetIndustriesCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public IndustryDto[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((IndustryDto[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2053.0")]
    public delegate void GetSalaryRangesCompletedEventHandler(object sender, GetSalaryRangesCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2053.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetSalaryRangesCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetSalaryRangesCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public SalaryRangeDto[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((SalaryRangeDto[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2053.0")]
    public delegate void RetrieveApplicantListByPagingCompletedEventHandler(object sender, RetrieveApplicantListByPagingCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2053.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class RetrieveApplicantListByPagingCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal RetrieveApplicantListByPagingCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public ApplicantDto[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((ApplicantDto[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2053.0")]
    public delegate void RetrieveAllApplicantsCompletedEventHandler(object sender, RetrieveAllApplicantsCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2053.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class RetrieveAllApplicantsCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal RetrieveAllApplicantsCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public ApplicantDto[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((ApplicantDto[])(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591